# Generated by tf-migrate 2.0.0-beta2


component "ec2_instance" {
  source = "terraform-aws-modules/ec2-instance/aws"

  inputs = {
    "ami"           = var.ami_id
    "instance_type" = var.instance_type
    "monitoring"    = true
    "name"          = var.instance_name
    "subnet_id"     = "subnet-04ac8df91e75657c9"
    "tags" = {
      Terraform   = "true"
      Environment = "dev"
    }
    "vpc_security_group_ids" = []
  }

  version = "~> 6.0"


  providers = {
    aws = provider.aws.this
  }
}


