# Generated by tf-migrate 2.0.0-beta1



# Note on AWS provider authentication:
# tf-migrate has identified the usage of AWS provider in your configuration.
# Templated varset store block for AWS tokens has been added in deployments.
# Please replace the placeholder varset ID with the actual varset ID that contains your AWS credentials before executing stacks.
# More on varset based authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate#authenticate-with-a-variable-set

store "varset" "tokens" {
  id       = "varset-xvfRyT1qNahGfpWm" # Replace with actual varset ID containing AWS credentials
  category = "env"
}

deployment "dev-workspace" {
  inputs = {
    instance_type = "t3.micro"
    ami_id        = "ami-0dee22c13ea7a9a67"
    instance_name = "stack-v3-test-dev-instance"
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
  }
  import = true
}



deployment "prod-workspace" {
  inputs = {
    instance_name = "stack-v3-test-prod-instance"
    instance_type = "t3.micro"
    ami_id        = "ami-0dee22c13ea7a9a67"
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
  }
  import = true
}



