# Generated by tf-migrate 2.0.0-beta3



# Note on AWS provider authentication:
# tf-migrate has identified the usage of AWS provider in your configuration.
# Templated varset store block for AWS tokens has been added in deployments.
# Please replace the placeholder varset ID with the actual varset ID that contains your AWS credentials before executing stacks.
# More on varset based authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate#authenticate-with-a-variable-set

store "varset" "tokens" {
  id       = "<PLACEHOLDER_FOR_AWS_TOKENS_VARSET_ID>"
  category = "env"
}

deployment "dev-workspace-deployment" {
  inputs = {
    instance_type = "t3.micro"
    ami_id        = "ami-0dee22c13ea7a9a67"
    aws_subnet_id = store.varset.tf-migrate-stack_dev-workspace-deployment.stable.aws_subnet_id
    region        = "ap-south-1"
    instance_name = "stack-v3-test-dev-instance"
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
  }
  migrate = true
}



deployment "prod-workspace-deployment" {
  inputs = {
    instance_name = "stack-v3-test-prod-instance"
    instance_type = "t3.micro"
    ami_id        = "ami-0dee22c13ea7a9a67"
    aws_subnet_id = store.varset.tf-migrate-stack_prod-workspace-deployment.stable.aws_subnet_id
    region        = "ap-south-1"
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
  }
  migrate = true
}

store "varset" "tf-migrate-stack_dev-workspace-deployment" {
  name     = "tf-migrate-stack_dev-workspace-deployment"
  category = "terraform"
}


store "varset" "tf-migrate-stack_prod-workspace-deployment" {
  name     = "tf-migrate-stack_prod-workspace-deployment"
  category = "terraform"
}


