# Generated by tf-migrate 2.0.0-beta1



# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate

store "varset" "tokens" {
  id       = "varset-xvfRyT1qNahGfpWm"
  category = "env"
}

deployment "dev-workspace" {
  inputs = {
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
    ami_id        = "ami-0dee22c13ea7a9a67"
    instance_name = "stack-v3-test-dev-instance"
    instance_type = "t3.micro"
  }
  import = true
}



deployment "prod-workspace" {
  inputs = {
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
    instance_name = "stack-v3-test-prod-instance"
    instance_type = "t3.micro"
    ami_id        = "ami-0dee22c13ea7a9a67"
  }
  import = true
}



