# Generated by tf-migrate 2.0.0-beta1


output "instance_id" {
  description = "The ID of the EC2 instance"
  value       = component.ec2_instance.id
  type        = string
}

output "instance_public_ip" {
  description = "The public IP address of the EC2 instance"
  value       = component.ec2_instance.public_ip
  type        = string
}

