# Generated by tf-migrate 2.0.0-beta1



provider "aws" "this" {
  config {
    region     = "ap-south-1"
    access_key = var.access_key
    secret_key = var.secret_key
    token      = var.session_token
  }
}

required_providers {
  aws = {
    source  = "hashicorp/aws"
    version = ">= 4.66.0, >= 5.0.0"
  }
}
