# Generated by tf-migrate 2.0.0-beta3



provider "aws" "this" {
  config {
    region     = var.region
    access_key = var.access_key
    secret_key = var.secret_key
    token      = var.session_token
  }
}

required_providers {
  aws = {
    source  = "hashicorp/aws"
    version = ">= 6.0.0, >= 6.28.0"
  }
}
